width_of_screen = 1400
hight_of_screen = 800
background_color = (100, 100, 200)
score_in_game_color = (0, 200, 0)
snake_color = "green"
start_position_of_snake_x_coord = width_of_screen // 2
start_position_of_snake_y_coord = hight_of_screen // 2
snake_start_speed = 2
max_snake_speed = 9
beautiful_snake = False
rainbow_snake = False
rainbow_colors = [(255, 0, 0), (255, 165, 0), (255, 255, 0), (0, 255, 0), (0, 0, 255), (75, 0, 130), (238, 130, 238)]
menu_width = 500
menu_height = 500
menu_left_bound = 500
menu_upper_bound = 200
table_of_records_upper_bound = 200
table_of_records_left_bound = 200
table_of_records_width = 1000
table_of_records_hight = 500
table_of_records_background_color = "indigo"
table_of_records_text_color = "white"
table_of_records_font = "Arial"
table_of_records_header_color = "blue"
table_of_records_header_font = "Sand"
table_of_records_header_size = 50
table_of_records_text_size = 30
settings_slider_length = 300
settings_colors_for_snake = ["green", "navy", "orange", "goldenrod", "yellow"]
after_game_entry_button_width = 50
max_len_name_in_scoreboard = 16
buttons_size_x = 50
buttons_size_y = 5
dist_between_buttons = 5
block_size = 20
border_width = 30
border_color = "black"
max_start_amount_of_walls = 10
walls_color = "black"
max_wall_random_length = block_size * 20
game_event_frequency = 40
food_colors = ["sienna", "blue", "cyan", "hotpink", "red"]
frames_between_food_spawns = 120
frames_between_speed_boosts = 300
increase_frames_between_speed_boosts = 600
max_unsuccessful_attemts_for_food_spawn = 20
max_unsuccessful_attemts_for_wall_spawn = 20
max_start_amount_of_food = 10
size_of_font_for_score = 30
fps = 60